### ISSUE TITLE
"No changes to code coverage between base and head branch" when fullCoverageDiff: false

### ISSUE THREAD

**Issue by ciesielskico** [anuraag016/Jest-Coverage-Diff#33]
![image](https://user-images.githubusercontent.com/17651898/141912048-441164c7-e59c-4dc7-bb44-00cf687a5c15.png)

As a test I have written some additional unit tests in the PR implementing this coverage diff tool but however many unit tests I add I still get the same message.

I run this on an Angular application which I have `jest` configured for with `jest-preset-angular`. The coverage is definitely being generated, because when I set `fullCoverageDiff` to `true` I get a wall of text with the whole coverage (which unfortunately is just unreadable given the length).

```
      - name: Run unit tests and check coverage
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false
          runCommand: npm run test:ci
          delta: 0.5
```

```
"test:ci": "ng test --ci --silent --bail --coverage --collect-coverage --coverage-directory='./' --coverage-reporters=json-summary",
```
