### ISSUE TITLE
Fetching base branch fails

### ISSUE THREAD

**Issue by mathiasmoeller** [anuraag016/Jest-Coverage-Diff#34]
Running the action fails when trying to fetch the base branch.

# Setup:
Github Actions runs on: `ubuntu-latest`
```
- uses: anuraag016/Jest-Coverage-Diff@master
  name: Jest Tests & Coverage Report
  with:
    runCommand: "npx jest --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary'"
    accessToken: ${{ secrets.GITHUB_TOKEN }}
    delta: 10
```
( the secret `secrets.GITHUB_TOKEN` is used by multiple workflows and is correct)

# Expected Behavior:
It should generate a coverage report

# Actual Behavior:
![image](https://user-images.githubusercontent.com/8833906/141984788-74d2ec94-45c1-4adc-807e-6347ba343d17.png)

Any idea what that problem could be? 
Thanks a lot already!
